export default {
    ADD_RESTAURANT: "ADD_RESTAURANT",
    UPDATE_RESTAURANT: "UPDATE_RESTAURANT",
    DELETE_RESTAURANT: "DELETE_RESTAURANT",
    ADD_REVIEW: "ADD_REVIEW",
    UPDATE_REVIEW: "UPDATE_REVIEW",
    DELETE_REVIEW: "DELETE_REVIEW",
}